# Use the official Node.js image as the base image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /opt/app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Strapi admin panel (if needed, otherwise you can remove this line)
RUN npm run build

# Expose the port Strapi runs on (default is 1337)
EXPOSE 1337

# Command to run the Strapi application
CMD ["npm", "start"]
